apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-hello
  namespace: default
spec:
  secretName: nginx-hello-stage-cert-tls
  dnsNames:
    - test.librelab.online
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-hello-gateway
  namespace: default
spec:
  selector:
    app: istio-ingress
    istio: ingress
  servers:
    - hosts:
        - "test.librelab.online"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: nginx-hello-stage-cert-tls
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-hello-vs
  namespace: default
spec:
  hosts:
    - "test.librelab.online"
  gateways:
    - nginx-hello-gateway
  http:
    - route:
        - destination:
            host: nginx-hello.default.svc.cluster.local
            port:
              number: 80