grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: user
    passwordKey: password
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
  ingress:
    enabled: false
  grafana.ini:
    server:
      root_url: https://monitoring.ewebsystems.net
    auth:
      disable_login_form: true
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      auto_login: true
      client_id: grafana
      client_secret: ""
      scopes: openid email profile roles
      auth_url: https://user-management.ewebsystems.net/realms/emotions/protocol/openid-connect/auth
      token_url: https://user-management.ewebsystems.net/realms/emotions/protocol/openid-connect/token
      api_url: https://user-management.ewebsystems.net/realms/emotions/protocol/openid-connect/userinfo
      use_pkce: true
      email_attribute_path: email
      login_attribute_path: preferred_username
      name_attribute_path: name
      role_attribute_path: "contains(realm_access.roles[*], 'grafana-admin') && 'Admin' || contains(realm_access.roles[*], 'grafana-editor') && 'Editor' || 'Viewer'"
      signout_redirect_url: https://user-management.ewebsystems.net/realms/emotions/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fmonitoring.ewebsystems.net%2Flogin
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://monitoring-kube-prometheus-stack-loki-gateway
      isDefault: false
      editable: true
      version: 1
      jsonData:
        maxLines: 1000
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: self-monitoring
prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
alloy:
  enabled: true
  config: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.source.kubernetes "pods_labeled_namespaces" {
      targets = discovery.kubernetes.pods.targets

      relabel_rules = [
        {
          action        = "keep"
          source_labels = ["__meta_kubernetes_namespace_label_logs"]
          regex         = "true"
        },


        { action="replace", source_labels=["__meta_kubernetes_namespace"], target_label="namespace" },
        { action="replace", source_labels=["__meta_kubernetes_pod_name"], target_label="pod" },
        { action="replace", source_labels=["__meta_kubernetes_pod_container_name"], target_label="container" },

        { action="replace", source_labels=["__meta_kubernetes_pod_label_app"], target_label="app" },
      ]

      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://monitoring-kube-prometheus-stack-loki-gateway/loki/api/v1/push"
        headers = {
          "X-Scope-OrgID" = "self-monitoring",
        }
      }
    }
