grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: user
    passwordKey: password
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
  ingress:
    enabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
      editable: true
      version: 1
      jsonData:
        maxLines: 1000
prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
alloy:
  enabled: true
  config: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://monitoring-kube-prometheus-stack-loki:3100/loki/api/v1/push"
      }
    }
