apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-setup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: git@github.com:ihor-sk/prod-cluster.git
    targetRevision: main
    path: setup/secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true