apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namecheap-webhook
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/kelvie/cert-manager-webhook-namecheap
    targetRevision: master
    path: deploy/cert-manager-webhook-namecheap
    helm:
      releaseName: namecheap-webhook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true