apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: user-management
  namespace: user-management
spec:
  instances: 1
  bootstrapAdmin:
    user:
      secret: admin-secret
  http:
    httpEnabled: true
  db:
    vendor: postgres
    host: user-management-primary.user-management.svc
    usernameSecret:
      name: user-management-pguser-keycloak
      key: user
    passwordSecret:
      name: user-management-pguser-keycloak
      key: password
  hostname:
    hostname: user-management.ewebsystems.net
  proxy:
    headers: xforwarded