apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-secret
  namespace: user-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: { .userManagementUser }
        password: { .userManagementPassword }        
data:
  - secretKey: userManagementUser
    remoteRef:
      key: prod/eweb/admin
      property: userManagementUser
  - secretKey: userManagementPassword
    remoteRef:
      key: prod/eweb/admin
      property: userManagementPassword