apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-postgres-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/CrunchyData/postgres-operator-examples.git
    path: helm/install
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pgo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - Validate=false
      - CreateNamespace=true