apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin.password: "{{ .argoPassword }}"
        admin.passwordMtime: "2025-10-09T12:34:56Z"
  data:
    - secretKey: argoPassword
      remoteRef:
        key: prod/eweb
        property: argoPassword
