global:
  domain: ""
  oauth: user-management.ems-customer.com
  backend: api.emotions.com.se
  namespace: eweb

tenants:
  - name: ewebtest

cluster:
  name: eweb


atlas:
  image: arigaio/atlas:latest
  sslmode: disable
  job:
    backoffLimit: 0