global:
  domain: ewebsystems.net
  backend: api.ewebsystems.net
  namespace: eweb
  tenantKeys:
    - ewebCoreSecret
    - ewebPortalSecret
    - ewebAdminInitSecret
tenants:
  - name: foo
  - name: bar
  - name: ewebtest
  - name: test
cluster:
  name: eweb
atlas:
  image: arigaio/atlas:latest
  sslmode: disable
  job:
    backoffLimit: 0
