global:
  domain: "ewebsystems.net"
  backend: api.emotions.com.se
  namespace: eweb

tenants:
  - name: ewebtest
  - name: foo

cluster:
  name: eweb


atlas:
  image: arigaio/atlas:latest
  sslmode: disable
  job:
    backoffLimit: 0