apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-stage
  namespace: istio-ingress
spec:
  secretName: stage-ewebsystems
  dnsNames:
    - "*.ewebsystems.net"
  issuerRef:
    kind: ClusterIssuer
    name: route53-letsencrypt-stage