apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-cluster-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:  test@librelab.online
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
      - dns01:
          webhook:
            groupName: acme.namecheap.com
            solverName: namecheap
            config:
              apiKeySecretRef:
                name: namecheap-credentials
                key: apiKey
              apiUserSecretRef:
                name: namecheap-credentials
                key: apiUser
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: admin@ewebsystems.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
      - selector:
          dnsZones:
            - "ewebsystems.net"
        dns01:
          route53:
            region: us-east-1
            accessKeyID: "AKIA4BIQSU3H5V2CGYXY"
            secretAccessKeySecretRef:
              name: route53-credentials-secret
              key: secret-access-key
