apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: route53-letsencrypt-stage
spec:
  acme:
    email: admin@ewebsystems.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: route53-letsencrypt-stage
    solvers:
      - selector:
          dnsZones:
            - "ewebsystems.net"
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z02977163LNV8CWDC2T99
            accessKeyID: "AKIA4BIQSU3H5V2CGYXY"
            secretAccessKeySecretRef:
              name: aws-credentials-secret
              key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-stage
  namespace: istio-ingress
spec:
  secretName: stage-ewebsystems
  dnsNames:
    - "*.ewebsystems.net"
  issuerRef:
    kind: ClusterIssuer
    name: route53-letsencrypt-stage
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
    istio: ingress
  servers:
    - hosts:
        - "*.ewebsystems.net"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: stage-ewebsystems