apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foo-user-secret
  namespace: eweb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: foo-user-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        initAdmin: "{{ .initAdmin }}"
  data:
    - secretKey: initAdmin
      remoteRef:
        key: prod/tenants/foo/user
        property: initAdmin
