{{- $ns := .Values.global.namespace | default "eweb" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "migration-keycloak-script"
  namespace: {{ $ns }}
data:
  run.sh: |-
    #!/bin/sh

    : "${TENANT:?TENANT is required}"

    start_ts="$(date -Is)"
    echo "=== [${TENANT}] START at ${start_ts} ==="

    # call the CLI for this tenant
    ls /tenants/foo
    cat /tenants/foo/uri
    java -jar /app/keycloak-config-cli.jar "${TENANT}"

    end_ts="$(date -Is)"
    echo "=== [${TENANT}] END rc=${rc} at ${end_ts} ==="