{{- $ns := .Values.global.namespace | default "eweb" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "migration-keycloak-script"
  namespace: {{ $ns }}
data:
  run.sh: |-
    #!/bin/sh

    : "${TENANT:?TENANT is required}"

    props="/tmp/${TENANT}.properties"
    
    start_ts="$(date -Is)"
    echo "=== [${TENANT}] START at ${start_ts} ==="

    {
      printf 'realm.name=%s\n'              "$(cat "/tenants/${TENANT}/dbname")"
      printf 'eweb.init.admin-secret=%s\n'  "$(cat "/tenants/${TENANT}/jdbc-uri")"
      printf 'eweb.client.secret=%s\n'      "$(cat "/tenants/${TENANT}/verifier")"
      printf 'eweb.core.secret=%s\n'        "$(cat "/tenants/${TENANT}/user")"
    } > "${props}"
    
    
    
    cat /tmp/${TENANT}.properties
    
    java -jar /app/keycloak-config-cli.jar "${TENANT}"

    end_ts="$(date -Is)"
    echo "=== [${TENANT}] END rc=${rc} at ${end_ts} ==="