{{- $ns := .Values.global.namespace | default "eweb" -}}
{{- $keys := .Values.global.tenantKeys | default (list) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "migration-keycloak-script"
  namespace: {{ $ns }}
data:
  run.sh: |-
    #!/bin/sh

    : "${TENANT:?TENANT is required}"

    props="/config/secret.properties"
    
    start_ts="$(date -Is)"
    echo "=== [${TENANT}] START at ${start_ts} ==="

    {
      printf 'realm.name=%s\n'  "$(cat "/tenants/${TENANT}/${TENANT}")"
      {{- range $k := $keys }}
      printf '{{ $k }}=%s\n' "$(cat "/tenants/${TENANT}/{{ $k }}")"
      {{- end }}
    } > "${props}"
    
    cat /config/${TENANT}.properties
    
    java -jar /app/keycloak-config-cli.jar

    end_ts="$(date -Is)"
    echo "=== [${TENANT}] END rc=${rc} at ${end_ts} ==="