apiVersion: apps/v1
kind: Deployment
metadata:
  name: eweb-client
  namespace:  {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eweb-client
  template:
    metadata:
      labels:
        app:  eweb-client
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: nginx-hello-html