apiVersion: apps/v1
kind: Deployment
metadata:
  name: eweb-client-portal
  namespace: eweb
  labels:
    app: eweb-client-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eweb-client-portal
  template:
    metadata:
      labels:
        app: eweb-client-portal
    spec:
      initContainers:
        - name: build-auth-config
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "[" > /app/config/auth_config.json
              {{- $lastIndex := sub (len .Values.tenants) 1 }}
              {{- range $i, $t := .Values.tenants }}
              SECRET=$(cat /secrets/{{ $t.name }}/secret)
              echo "{\"name\": \"{{ $t.name }}\", \"secret\": \"${SECRET}\"}" >> /app/config/auth_config.json
              {{- if ne $i $lastIndex }},{{ end }}
              {{- end }}
              echo "]" >> /app/config/auth_config.json
          volumeMounts:
            - name: auth-config
              mountPath: /app/config
            {{- range $t := .Values.tenants }}
            - name: {{ $t.name }}-tenant-secret
              mountPath: /secrets/{{ $t.name }}
              readOnly: true
            {{- end }}
      containers:
        - name: eweb-client-portal
          imagePullPolicy: Always
          image: "827352852175.dkr.ecr.eu-north-1.amazonaws.com/eweb-client-portal:latest"
          ports:
            - name: http
              containerPort: 3000
              protocol: "TCP"
          env:
            - name: NEXT_PUBLIC_EWEB2_URL
              value: "https://api.ewebsystems.net"
            - name: KEYCLOAK_CLIENT_ID
              value: "eweb-client-portal"
            - name: KEYCLOAK_ISSUER
              value: "https://user-management.ewebsystems.net/realms/"
            - name: EWEB_DOMAIN
              value: "ewebsystems.net"
            - name: AUTH_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: client-portal-auth
                  key: auth_config.json
          volumeMounts:
            - name: auth-config
              mountPath: /app/config

      volumes:
        - name: auth-config
          emptyDir: {}
        {{- range .Values.tenants }}
        - name: {{ .name }}-tenant-secret
          secret:
            secretName: {{ .name }}-tenant-secret
        {{- end }}