apiVersion: v1
kind: ConfigMap
metadata:
  name: client-portal-config
  namespace: eweb
data:
  NEXT_PUBLIC_EWEB2_URL: "https://api.ewebsystems.net"
  KEYCLOAK_CLIENT_ID: "eweb-client-portal"
  KEYCLOAK_ISSUER: "https://user-management.ewebsystems.net/realms/"
  EWEB_DOMAIN: "ewebsystems.net"
  AUTH_CONFIG: '[{ "name": "foo", "secret": "LB64PXh9B0Y2nOaDqg7QPPGud8rp3It1" }, { "name": "bar", "secret": "rQb9JMtDg8EnrDjHFob5nLqZS5kbLeej" }]'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eweb-client-portal
  namespace: eweb
  labels:
    app: eweb-client-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eweb-client-portal
  template:
    metadata:
      labels:
        app: eweb-client-portal
    spec:
      containers:
        - name: eweb-client-portal
          imagePullPolicy: Always
          image: "827352852175.dkr.ecr.eu-north-1.amazonaws.com/eweb-client-portal:latest"
          ports:
            - name: http
              containerPort: 3000
              protocol: "TCP"
          envFrom:
            - configMapRef:
                name: client-portal-config
---
apiVersion: v1
kind: Service
metadata:
  name: eweb-client-portal
  namespace: eweb
  labels:
    app: eweb-client-portal
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: "http"
      name: http
      protocol: "TCP"
  selector:
    app: eweb-client-portal