apiVersion: v1
kind: Service
metadata:
  name: eweb-client-portal
  namespace: eweb
  labels:
    app: eweb-client-portal
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: "http"
      name: http
      protocol: "TCP"
  selector:
    app: eweb-client-portal