{{- range $t := .Values.tenants }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-ewebsystems-{{ $t.name }}
  namespace: eweb
spec:
  hosts:
    - "{{ $t.name }}.ewebsystems.net"
  gateways:
    - istio-ingress/main-gateway
  http:
    - route:
        - destination:
            host: eweb-client-service.eweb.svc.cluster.local
            port:
              number: 80
---
{{- end }}
