apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mychart.fullname" . }}-print-tenants
  labels: {{- include "mychart.labels" . | nindent 4 }}
  namespace: eweb
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: print-tenants
          image: busybox:1.36
          command:
            - /bin/sh
            - -ec
            - |
              echo "Listing tenants..."
              {{- range $i, $t := .Values.tenants }}
              echo "Tenant: {{ $t.name }}"
              {{- end }}
