apiVersion: v1
kind: Secret
metadata:
  name: broker-eweb-user
  namespace: eweb
stringData:
  password: "qwerty"
  username: "eweb"
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: eweb-broker
  namespace: eweb
spec:
  replicas: 1
  service:
    spec:
      type: ClusterIP
  override:
    statefulSet:
      spec:
        template:
          spec:
            initContainers:
              - name: setup-container
                securityContext:
                  runAsNonRoot: false
                  runAsUser: 0
                  allowPrivilegeEscalation: false
            securityContext:
              fsGroup: 999
              fsGroupChangePolicy: OnRootMismatch
            containers:
              - name: rabbitmq
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 999
                  runAsGroup: 999
                  allowPrivilegeEscalation: false
                env:
                  - name: RABBITMQ_DEFAULT_USER
                    valueFrom:
                      secretKeyRef:
                        name: broker-eweb-user
                        key: username
                  - name: RABBITMQ_DEFAULT_PASS
                    valueFrom:
                      secretKeyRef:
                        name: broker-eweb-user
                        key: password
                resources:
                  requests:
                    cpu: "250m"
                    memory: "512Mi"
                  limits:
                    cpu: "1"
                    memory: "1Gi"
              - name: netbird-agent
                image: netbirdio/netbird:latest
                imagePullPolicy: Always
                securityContext:
                  runAsNonRoot: false
                  runAsUser: 0
                  privileged: true
                  capabilities:
                    add: ["NET_ADMIN","SYS_RESOURCE","SYS_ADMIN"]
                env:
                  - name: NB_SETUP_KEY
                    value: "A0566152-55A8-4D1E-9F63-D94BFDFD0958"
                  - name: NB_HOSTNAME
                    value: "netbird-k8s-router"
                  - name: NB_LOG_LEVEL
                    value: "debug"
                  - name: NB_MANAGEMENT_URL
                    value: "https://vpn.librelab.online"
                  - name: NB_LOG_FILE
                    value: "console"
                resources:
                  limits:
                    cpu: 100m
                    memory: 128Mi
                  requests:
                    cpu: 50m
                    memory: 64Mi