apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-management-secret
  namespace: eweb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: user-management-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        username:  {{ printf "{{ .userManagementUser }}" | quote }}
        password:  {{ printf "{{ .userManagementPassword }}" | quote }}
  data:
    - secretKey: userManagementPassword
      remoteRef:
        key: prod/eweb/admin
        property: userManagementPassword
    - secretKey: userManagementUser
      remoteRef:
        key: prod/eweb/admin
        property: userManagementUser
