apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: user-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources
    targetRevision: 26.4.0
    directory:
      recurse: false
      include: |
        kubernetes/keycloaks.k8s.keycloak.org-v1.yml
        kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
        kubernetes/kubernetes.yml
